### ISSUE TITLE
(feature/bug) brainfuck int size is not accounted for in compiler

### ISSUE THREAD

**Issue by ultrabear** [BobDotCom/bftools#1]
In standard brainfuck, the memory buffer is an array of 8 bit bytes, giving a set range of numbers it is in
Some implementations have options for 16 and or 32 bit memory cell sizes too
However, the implementation used by this compiler uses pythons underlying bigint implementation, which has no bound aside from memory constraints, this makes a trivial program such as the ascii range printer `.+[.+]` never actually capable of exiting, as instead of overflowing at 255 it would continue beyond, past 1<<16 and 1<<32 limits as well, ending only when the python program runs out of memory to store the int
While different implementations are valid and fun to see (ex: 16 and 32 bit is a branch of the standard), there should at least be a system to compile to 8 bit brainfuck as that is the default standard of the language (probably best handled by a bytearray in python)

**Comment by BobDotCom** [comment]
Good catch! I'll see how I can implement this.

**Comment by BobDotCom** [comment]
Took long enough, but I finally got to this lol. Implemented in c027d012fd31807fba2eff4485b794db56176fa3, released in [v0.3.0](https://pypi.org/project/bftools/0.3.0/).

**Comment by BobDotCom** [comment]
The implementation has been improved and the changes will be released in v1.0.0. A quick summary:

 - Support for overflow was added, and now functions correctly
 - Support for modifying the length of the memory has been added
 - Support for changing the int size has been added. Supported sizes include 8, 16, 32, and 64. This is currently not functioning correctly but will be resolved before release.
